bestpub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('breweries.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

breweries/urls.py
from django.urls import path

from . import views


app_name = 'breweries'

urlpatterns = [
    path('recreate_types/', views.create_types, name='create_types'),
    path('download_data/', views.download_data, name='download_data'),
    path('brewery/add', views.BreweriesCreateView.as_view(), name='create'),
    path('brewery/<int:pk>/edit', views.BreweriesUpdateView.as_view(), name='edit'),
    path('brewery/<int:pk>/delete', views.BreweriesDeleteView.as_view(), name='delete'),
    path('brewery/<int:pk>', views.BreweriesDetailView.as_view(), name='detail'),
    path('', views.BreweriesListView.as_view(), name='list'),
]

breweries/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext as _


class BreweryTypes(models.Model):
    name = models.CharField(
        verbose_name='Name',
        max_length=50
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Brewery Type'
        verbose_name_plural = 'Brewery Types'


class Breweries(models.Model):
    name = models.CharField(
        verbose_name='Name',
        max_length=150,
        unique=True,
    )

    website_url = models.URLField(
        verbose_name='Website URL',
        max_length=200,
        blank=True,
        null=True,
    )

    brewery_type = models.ForeignKey(
        BreweryTypes    ,
        verbose_name='Brewery type',
        on_delete=models.CASCADE,
    )

    city = models.CharField(
        verbose_name='City',
        max_length=150,
    )

    state = models.CharField(
        verbose_name='State',
        max_length=150,
        null=True,
        blank=True,
    )

    country = models.CharField(
        verbose_name='Country',
        max_length=150,
    )

    phone = models.CharField(
        verbose_name='Phone',
        max_length=15,
        blank=True,
        null=True,
    )

    updated_at = models.DateTimeField(
        verbose_name='Updated',
        auto_now_add=False,
        auto_now=True,
    )

    created_at = models.DateTimeField(
        verbose_name='Created',
        auto_now_add=True,
        auto_now=False,
    )

    def get_absolute_url(self):
        return reverse('breweries:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Brewery'
        verbose_name_plural = 'Breweries'

breweries/views.py
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from . import helpers
from .models import Breweries

from breweries.openbrewerydb import OpenBreweryAPI, OpenBreweryException


class BreweriesListView(ListView):
    model = Breweries
    paginate_by = 5


class BreweriesDetailView(DetailView):
    model = Breweries


class BreweriesDeleteView(DeleteView):
    model = Breweries
    success_url = reverse_lazy('breweries:list')


class BreweriesCreateView(CreateView):
    model = Breweries
    fields = (
        'name',
        'website_url',
        'brewery_type',
        'city',
        'state',
        'country',
        'phone',
    )


class BreweriesUpdateView(UpdateView):
    model = Breweries
    fields = (
        'name',
        'website_url',
        'brewery_type',
        'city',
        'state',
        'country',
        'phone',
    )


def download_data(request):
    per_page = request.GET.get('per_page')
    page = request.GET.get('page')
    by_type = request.GET.get('by_type')
    by_city = request.GET.get('by_city')

    if request.GET.get('clear_all', 'false') == 'true':
        helpers.clear_breweries_table()

    breweries_api = OpenBreweryAPI()
    try:
        breweries = breweries_api.get_list(
            per_page=per_page,
            page=page,
            by_type=by_type,
            by_city=by_city,
        )
    except OpenBreweryException:
        return HttpResponseServerError('Not today')

    not_created_breweries = []

    for brewery in breweries:
        try:
            helpers.create_brewery(brewery)
        except:
            not_created_breweries.append(brewery['name'])

    context = {
        'not_created_breweries': not_created_breweries
    }

    return render(request, 'breweries/request_completed.html', context)


def create_types(request):
    helpers.create_brewery_types()

    return render(request, 'breweries/request_completed.html')

breweries/templates/breweries/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	{% block title %}{% endblock title %}

	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

	{% block header %}
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
			<div class="container">
				<a class="navbar-brand" href="/">Bestpub</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a
								class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
								href="{% url 'breweries:list' %}">
								Breweries
							</a>
						</li>
						<li class="nav-item">
							<a
								class="nav-link {% if 'brewery/add' in request.path %}active{% endif %}"
								href="{% url 'breweries:create' %}">
								Add new brewery
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	{% endblock header %}

	{% block content %}{% endblock content %}

</body>
</html>

breweries/templates/breweries/breweries_confirm_delete.html
{% extends 'breweries/base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<form method="post">
					{% csrf_token %}
					<p>Are you sure you want to delete "{{ object.name }}"?</p>
					<input class="btn btn-danger" type="submit" value="Yes. Delete">
			</form>
			</div>
		</div>
	</div>
{% endblock content %}

breweries/templates/breweries/breweries_detail.html
{% extends 'breweries/base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">{{ object.name }}</h5>
						<p class="card-text">Type: {{ object.brewery_type }}</p>
						<p class="card-text">City: {{ object.city }}</p>
						{% if object.state %}
							<p class="card-text">State: {{ object.state }}</p>
						{% endif %}
						<p class="card-text">Country: {{ object.country }}</p>
						{% if object.phone %}
							<p class="card-text">Phone: {{ object.phone }}</p>
						{% endif %}
						<p class="card-text">Updated: {{ object.updated_at }}</p>
						<p class="card-text">Created: {{ object.created_at }}</p>
						{% if object.website_url %}
							<p>
								Website:&nbsp;
								<a
									href="{{ object.website_url }}"
									rel="noreferrer noopenner"
									target="_blank">
									{{ object.website_url }}
								</a>
							</p>
						{% endif %}
						<a href="{% url 'breweries:edit' object.id %}" class="btn btn-primary">Edit</a>
						<a href="{% url 'breweries:delete' object.id %}" class="btn btn-danger">Delete</a>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

breweries/templates/breweries/breweries_form.html
{% extends 'breweries/base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<form method="post" class="form">
					{% csrf_token %}
					{{ form.as_p }}
					<input class="btn btn-primary" type="submit" value="Save">
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

breweries/templates/breweries/breweries_list.html
{% extends 'breweries/base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			{% for brewery in object_list %}
				<div class="col-12">

					<div class="card mb-4">
						<div class="card-body">
							<h5 class="card-title">
								<a href="{% url 'breweries:detail' brewery.pk %}">{{ brewery.name }}</a>
							</h5>
							<p class="card-text">City: {{ brewery.city }}</p>
							{% if brewery.website_url %}
								<p>
									Website: <a href="{{ brewery.website_url }}" target="_blank">{{ brewery.website_url }}</a>
								</p>
							{% endif %}
						</div>
					</div>

				</div>
			{% endfor %}
		</div>

		<div class="row">
			<ul class="pagination">
				<li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
					{% if page_obj.has_previous %}
						<a
							class="page-link"
							href="?page={{ page_obj.previous_page_number }}">
							Previous
						</a>
					{% else %}
						<span class="page-link">Previous</span>
					{% endif %}
				</li>
				<li class="page-item">
					<span class="page-link">{{ page_obj.number }}</span>
				</li>
				</li>
				<li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
					{% if page_obj.has_next %}
						<a
							class="page-link"
							href="?page={{ page_obj.next_page_number }}">
							Next
						</a>
					{% else %}
						<span class="page-link">Next</span>
					{% endif %}
				</li>
			</ul>
		</div>
	</div>
{% endblock content %}

breweries/templates/breweries/request_completed.html
{% extends 'breweries/base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12">
			<p>Your request is completed, Fellow!</p>

			{% if not_created_breweries %}
				<p>Failed to create following breweries:</p>
				{% for brewery in not_created_breweries %}
					<p>{{ brewery }}</p>
				{% endfor %}
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}